# Dockerfile.deploy

FROM golang:1.14 as builder

ENV APP_HOME /go/src/mathapp

WORKDIR $APP_HOME
COPY src/ .

RUN go mod download
RUN go mod verify
RUN go build -o mathapp

FROM debian:buster

ENV APP_HOME /go/src/mathapp
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY src/conf/ conf/
COPY src/views/ views/
COPY --from=builder $APP_HOME/mathapp $APP_HOME

EXPOSE 8010
CMD ["./mathapp"]